### ISSUE TITLE
编译有个小问题，需要改一下lib/build.gradle才能编过。要不改一下？

### ISSUE THREAD

**Issue by jtbuaa** [promeG/TinyPinyin#1]
FAILURE: Build failed with an exception.

* Where:
Build file '/home/jingtao/git/TinyPinyin/lib/build.gradle' line: 101

* What went wrong:
A problem occurred evaluating project ':lib'.
> Could not find property 'bintray_user' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@269bb42b.

**Comment by promeG** [comment]
谢谢！ 我会尽快更改一下。
