### ISSUE TITLE
Pinyin.init(Pinyin.newConfig().with(CnCityDict.getInstance(this)) 类型不匹配？

### ISSUE THREAD

**Issue by timshinlee** [promeG/TinyPinyin#11]
谢谢作者分享这么强大的库，不过我调用这个城市字典的初始化方法会报类型不匹配，能不能帮我看一下是什么问题，谢谢！
with(com.github.promeg.pinyinhelper.PinyinDict) in Config cannot be applied
to (com.github.promeg.tinypinyin.lexicons.android.cncity.CnCityDict)

**Comment by promeG** [comment]
Hi,

请问你是用在Android项目中吗？如果是的话，请修改build.grale

保留：
compile 'com.github.promeg:tinypinyin-lexicons-android-cncity:2.0.1'

移除：
compile 'com.github.promeg:tinypinyin-lexicons-java-cncity:2.0.1'

请检查代码import的是否为com.github.promeg.tinypinyin.lexicons.android.cncity.CnCityDict


如果仍有问题，请贴出你的build.gradle文件和import的类名。

谢谢！

**Comment by timshinlee** [comment]
是Android项目哈

gradle中的依赖：
compile 'com.github.promeg:tinypinyin:2.0.1' // TinyPinyin核心包，约80KB
compile 'com.github.promeg:tinypinyin-lexicons-android-cncity:2.0.1' // 可选，适用于Android的中国地区词典

import的类名：
import com.github.promeg.tinypinyin.lexicons.android.cncity.CnCityDict;

点击跳转的类声明
public final class CnCityDict extends AndroidAssetDict {}

**Comment by promeG** [comment]
我试了一下是ok的：

```
Pinyin.init(Pinyin.newConfig().with(CnCityDict.getInstance(MainActivity.this)));
```

请检查下是否传入了Context参数。

**Comment by timshinlee** [comment]
@promeG 传入的是Activity没错，重建了个工程试一下还是不行，那只能不添加字典了，谢谢你！

**Comment by promeG** [comment]
@timshinlee 

2.0.2版本已修复此bug，谢谢！

**Comment by timshinlee** [comment]
@promeG 好的，十分感谢！可以用了

**Comment by promeG** [comment]
不客气。

**Comment by DreamerLeon** [comment]
@promeG 3.0.0版本又出西安这个问题了

**Comment by promeG** [comment]
@DreamerLeon 请使用当前稳定版本2.0.3，已更新README
