### ISSUE TITLE
阿坝藏族羌族自治州获取拼音结果为'﻿-ABAZANGZUQIANGZUZIZHIZHOU'

### ISSUE THREAD

**Issue by HeyManImMoy** [promeG/TinyPinyin#16]
![image](https://cloud.githubusercontent.com/assets/10720800/23821167/2a5a86a0-0665-11e7-8493-7a0375d27a98.png)
其中-复制出来是粘贴不了的 ，是不是多了特殊字符。

**Comment by HeyManImMoy** [comment]
设置Pinyin.init(Pinyin.newConfig().with(CnCityDict.getInstance(HFApplication.getAppContext())));之后才出现该bug，所以应该是
![image](https://cloud.githubusercontent.com/assets/10720800/23821236/18d156c8-0667-11e7-9c00-434348764072.png)这个文件出问题

**Comment by promeG** [comment]
@HeyManImMoy 已修复，请升级到2.0.3版本。
