### ISSUE TITLE
Android Studio 用jdk 1.8编译提示下面错误

### ISSUE THREAD

**Issue by dalufine** [promeG/TinyPinyin#17]
Error:Execution failed for task ':***:transformClassesWithPreJackPackagedLibrariesForDebug'.
> com.android.sched.scheduler.RunnerProcessException: Error during 'ReachingDefinitions' runner on 'static void com.github.promeg.pinyinhelper.PinyinCode1.<clinit>() (PinyinCode1.java:13-61)': Java heap space

build中启用了jack
jackOptions {
                   enabled true
       }

**Comment by promeG** [comment]
与 #6 重复。

不会修复此issue，原因是jack toolchain已经被Google弃用。

参考：

http://tools.android.com/tech-docs/jackandjill
