### ISSUE TITLE
添加词典报错

### ISSUE THREAD

**Issue by aoyuanbo** [promeG/TinyPinyin#18]
java.lang.NoClassDefFoundError: org/ahocorasick/trie/Trie

**Comment by promeG** [comment]
你好，请问用的是什么版本呢？build.gradle贴出来看看

**Comment by promeG** [comment]
猜想是老版本中，aar缺失依赖导致。新版已修复此问题。

**Comment by zybieku** [comment]
新版根本down不下来，Trie这个类从哪里依赖过来的，可以提供新版的地址嘛，你这个中央仓库都挂了好久了
