### ISSUE TITLE
java用的tinyPinyin报错

### ISSUE THREAD

**Issue by Elysionxi** [promeG/TinyPinyin#19]
![image](https://cloud.githubusercontent.com/assets/15983300/26244380/fadd4956-3cc1-11e7-9e43-212ba717c327.png)

Pinyin.init(Pinyin.newConfig().with(CnCityDict.geInstance()));
这行报错，随后改为自定自定义字典依旧报错

**Comment by promeG** [comment]
@Elysionxi 你好，请问用的TinyPinyin版本是多少？

**Comment by Elysionxi** [comment]
我用的最新版的

**Comment by promeG** [comment]
使用2.0.3版本未能重现问题。
