### ISSUE TITLE
新换了studio2.0，发现有几个新的编译错误

### ISSUE THREAD

**Issue by jtbuaa** [promeG/TinyPinyin#2]
Information:Using javac 1.7.0_51 to compile java sources
Information:java: Errors occurred while compiling module 'lib'
Information:15-12-23 下午1:40 - Compilation completed with 8 errors and 0 warnings in 1s 148ms
/home/jingtao/git/TinyPinyin/lib/src/jmh/java/com/github/promeg/pinyinhelper/PinyinSampleBenchmark.java
Error:(4, 35) java: package org.openjdk.jmh.annotations does not exist
Error:(5, 32) java: package net.sourceforge.pinyin4j does not exist
Error:(14, 6) java: cannot find symbol
  symbol:   class Benchmark
  location: class com.github.promeg.pinyinhelper.PinyinSampleBenchmark
Error:(19, 6) java: cannot find symbol
  symbol:   class Benchmark
  location: class com.github.promeg.pinyinhelper.PinyinSampleBenchmark
Error:(24, 6) java: cannot find symbol
  symbol:   class Benchmark
  location: class com.github.promeg.pinyinhelper.PinyinSampleBenchmark

**Comment by promeG** [comment]
谢谢反馈！

我会尽快在2.0上测试一下。

**Comment by promeG** [comment]
as 2.1.2运行正常。
