### ISSUE TITLE
多音字问题

### ISSUE THREAD

**Issue by ApprenticeMythology** [promeG/TinyPinyin#22]
比如 重庆，重量，要手动维护这样的多音字词典，
有没有打算支持这样的功能，输入 "重"，直接返回 CHONG, ZHONG 这两个拼音？不再依赖外部维护的词典？

**Comment by promeG** [comment]
你好，

TinyPinyin的设计思路认为：绝大部分情况下，一个多音字到底该取哪个拼音，是由其所处的词决定的。

因此不会抛开“词”来考虑“单字符”的多音。

谢谢！
