### ISSUE TITLE
可以支持汉字转注音吗？

### ISSUE THREAD

**Issue by jhwsx** [promeG/TinyPinyin#47]

**Comment by VaslD** [comment]
你说到注音是说ㄅㄆㄇㄈ这种文字吗？

把 https://github.com/promeG/TinyPinyin/blob/master/lib/src/main/java/com/github/promeg/pinyinhelper/PinyinData.java 这个文件里的拉丁字母写的拼音表改成注音文字表就可以了。

**Comment by jhwsx** [comment]
谢谢。
