### ISSUE TITLE
com.android.sched.scheduler.RunnerProcessException: Error during 'CodeItemBuilder' runner on 'static void com.github.promeg.pinyinhelper.PinyinCode1.<clinit>() (PinyinCode1.java:13-61)': Java heap space

### ISSUE THREAD

**Issue by yuhanghate** [promeG/TinyPinyin#6]
我在项目中使用jack,编译时出现问题

**Comment by promeG** [comment]
Hi,

目前该项目使用Intellij IDEA编译，正在开发的2.0版本支持Android Studio编译（尚未上传）。

谢谢！

**Comment by promeG** [comment]
2.0版本已支持Android Studio，但不支持Jack编译链。

**Comment by anushamuggle** [comment]
Hi, I'm facing the same problem. What was the fix here?

**Comment by promeG** [comment]
@anushamuggle

This issue won't be fixed.

Jack toolchain is deprecated by Google.


Reference: 
http://tools.android.com/tech-docs/jackandjill
