### ISSUE TITLE
pom鏈結掛了,沒有沒有可以提供aar或是相關的Lib

### ISSUE THREAD

**Issue by CiaShangLin** [promeG/TinyPinyin#70]
pom鏈結掛了,沒有沒有可以提供aar或是相關的Lib
專案太舊了clone下來也編譯不過

**Comment by Anthoooooooony** [comment]
我保留了之前 2.0.3 版本的 jar 包，可以以文件方式引入。GitHub不允许上传 jar 文件所以打了个包。

[jar.tar.gz](https://github.com/user-attachments/files/17894253/jar.tar.gz)

**Comment by promeG** [comment]
@CiaShangLin  jcenter已无法下载，请在gradle中文件使用阿里云maven仓库代替：

build.gradle示例：

```
  repositories {
    maven {
      url 'https://maven.aliyun.com/repository/public'
    }
    mavenCentral()
  }

```

build.gradle.kts示例：

```
repositories {
    maven("https://maven.aliyun.com/repository/public")
    mavenCentral()
}
```
